### ISSUE TITLE
Package.json incorrectly formatted

### ISSUE THREAD

**Issue by mAAdhaTTah** [then/is-promise#12]
I'm getting a failure on a Travis build from this update. Looks like you just added a dual-module package. With `type: module` in the package.json, I _think_ `main` should point to the ESM build or needs the `.cjs` extension.

Build is here: https://travis-ci.org/github/mAAdhaTTah/brookjs/jobs/679426871

I haven't written a dual module package, so I could be wrong on the fix, but the current implementation is def broken, unfortunately.

**Comment by RyanZim** [comment]
Yep, needs `.cjs` extension.

**Comment by onhate** [comment]
for those using yarn and it's breaking because this is a nested dependency add this temporarily to package.json

```
"resolutions": {
    "is-promise": "2.1.0"
  },
```

**Comment by dada513** [comment]
yeah this broke my package

**Comment by nprail** [comment]
This issue breaks `@angular/cli` as well. 

Solved it by pinning the version in the `package-lock.json` file like so:
```
"is-promise": {
  "version": "2.1.0",
  "resolved": "https://registry.npmjs.org/is-promise/-/is-promise-2.1.0.tgz",
  "integrity": "sha1-eaKp7OfwlugPNtKy87wWwf9L8/o=",
  "dev": true
}
```

**Comment by RyanZim** [comment]
PR opened: https://github.com/then/is-promise/pull/15

**Comment by evicent** [comment]
solution here!

npm remove is-promise
npm install is-promise@2.1.0

Try and let your comments

**Comment by dalu** [comment]
> This issue breaks `@angular/cli` as well.
> 
> Solved it by pinning the version in the `package-lock.json` file like so:
> 
> ```
> "is-promise": {
>   "version": "2.1.0",
>   "resolved": "https://registry.npmjs.org/is-promise/-/is-promise-2.1.0.tgz",
>   "integrity": "sha1-eaKp7OfwlugPNtKy87wWwf9L8/o=",
>   "dev": true
> }
> ```

doesn't work for me, it's already at that version in the package-lock.json, everything is identical
