### ISSUE TITLE
angular "ng update" leads to errors because of this package

### ISSUE THREAD

**Issue by dalu** [then/is-promise#18]
```
ng update                                   
Your global Angular CLI version (9.1.3) is greater than your local
version (8.3.20). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
The installed Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Unknown error: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /tmp/.ng-temp-packages-l4NeIR/node_modules/is-promise/index.js
require() of ES modules is not supported.
require() of /tmp/.ng-temp-packages-l4NeIR/node_modules/is-promise/index.js from /tmp/.ng-temp-packages-l4NeIR/node_modules/run-async/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /tmp/.ng-temp-packages-l4NeIR/node_modules/is-promise/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /tmp/.ng-temp-packages-l4NeIR/node_modules/is-promise/package.json.
```

**Comment by RyanZim** [comment]
Duplicate of https://github.com/then/is-promise/issues/12; pin to v2.1.0 until the issue is fixed.

**Comment by semills17** [comment]
I just got the same error

Unknown error: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\is-promise\index.js
require() of ES modules is not supported.
require() of C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\is-promise\index.js from C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\run-async\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\is-promise\index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\is-promise\package.json.

**Comment by dalu** [comment]
> Duplicate of #12; pin to v2.1.0 until the issue is fixed.

I'll close this then and continue in #12
