### ISSUE TITLE
[[IsHTMLDDA]] Internal Slot objects aren't reported as promises

### ISSUE THREAD

**Issue by xfix** [then/is-promise#24]
An object with [[IsHTMLDDA]] internal slot that happen to have callable `then` property won't be reported as a promise, even if the ECMAScript considers such objects to be promises.

**Comment by ForbesLindesay** [comment]
Can you please supply some example code that fails?

**Comment by xfix** [comment]
```javascript
document.all.then = () => {}
console.log(isPromise(document.all))
```

**Comment by ForbesLindesay** [comment]
Thanks for clarifying. I think this is an acceptable edge case, since it's very specific to `document.all` which tries extremely hard to pretend to be undefined. Most native HTML objects would be treated as Promises if you added a `.then` method.
