### ISSUE TITLE
Include 'index.d.ts' into the published package

### ISSUE THREAD

**Issue by mvila** [then/is-promise#26]
@ForbesLindesay I am pleased to see that you recently added a type definition for `isPromise()`, but unfortunately, it seems you forgot to include it in the published package. Could you add it, please?

**Comment by ForbesLindesay** [comment]
I will do so. I'll make it a major release along with the ESM support so as not to accidentally break anything again.

**Comment by ForbesLindesay** [comment]
Covered by #31
