### ISSUE TITLE
Code readability

### ISSUE THREAD

**Issue by muv1** [then/is-promise#33]
Unless you just have a strong desire for a single line package, this more
readable code is functionally identical as far as I can tell:

~~~js
function isPromise(obj) {
   switch (typeof obj) {
   case 'undefined':
      return false;
   case 'function':
   case 'object':
      return typeof obj.then === 'function';
   default:
      return false;
   }
}
~~~

**Comment by ForbesLindesay** [comment]
I believe you've missed the `null` handling, but I don't really think it's a meaningful improvement in readability.

**Comment by muv1** [comment]
Understood.

Personally I just found this really disttasteful:

~~~
 !!obj
~~~

Coming from a strongly typed language like Go, thats not allowed. Only booleans can use the Not statement, so that would be an error. Granted JavaScript is not Go, but I think that using loose typing in general is bad, even if its allowed by the language.

**Comment by ForbesLindesay** [comment]
`!!` is a very common thing to see in JavaScript as a way of fairly explicitly casting from null/empty string/etc. to boolean.

**Comment by muv1** [comment]
@ForbesLindesay yeah its common, but its terrible coding style.

By just even using one `!`, youre coercing the argument into another type. Here
is what happen if you try that with Go:

~~~go
package main
func main() {
   n1 := 10
   b1 := ! n1 // invalid operation: ! int
   println(b1)
}
~~~

Again, I understand that JavaScript is not Go, but its easy enough to see if
something is `undefined`, without having to do type coercion. My original code
snippet is just one example.
