### ISSUE TITLE
Invalid configuration error

### ISSUE THREAD

**Issue by RodolfoGS** [then/is-promise#44]
When I run a React Native app, the following warning appear in the console.

Someone know what is this?

```
Package is-promise has been ignored because it contains invalid configuration.
Reason: Package subpath './package.json' is not defined by "exports" in node_modules/is-promise/package.json
```

**Comment by ForbesLindesay** [comment]
I think it means that you have some code that depends on `is-promise@*`(or anything that would match version 3.0.0 or 4.0.0) that does `require('is-promise/package.json')` or `import 'is-promise/package.json';`. This is a breaking change between is-promise 2.x.x and 3.x.x

You can see this in the release notes for 3.0.0: https://github.com/then/is-promise/releases/tag/3.0.0
